### ISSUE TITLE
Word list for all other languages?

### ISSUE THREAD

**Issue by ghost** [wlauyeung/Skribblio-Word-Bank#1]
Please give me more comprehensive word data. I want others to be able to see the full word list in their language, just in case they are wondering (not that I've actually encountered anyone who wants it lol). It can be in the JSON format identical to the other ones that are already in this repo.

I'm not sure how you would collect difficulty, though. Could you explain how that would happen? I couldn't find it in the Skribblio-Bot repository's code.

Edit: when I was editing my notification settings I accidentally turned off email notifications for conversations like this

**Comment by wlauyeung** [comment]
I'll try to add the raw word lists later when I have some free time. 

There's a branch called `most_picked` in the bot repo that includes the source code of how the difficulty ratings were calculated. But the tldr is that the bot would join a public game and sees which word is currently being drawn and sums up the number of correct guessers at the end of the round. The sum is then divided by the total number of guessers in that round (the bot is excluded in the calculation) to give a rough estimate of how difficult a word is to draw by players.

Forgot to mention, only the English word list have real difficulty ratings. The ratings for the other languages just have 0 as placeholder.

**Comment by ghost** [comment]
Oh, I see. By raw word lists, you literally meant an array of just words, not the other languages. Speaking of which, I'm pretty sure the algorithm that you've coded works to calculate unbiased difficulty because the bot isn't included, but I'm just wondering: why do the other languages have the number of times picked and the difficulty as just a placeholder of `0`?

**Comment by wlauyeung** [comment]
The other languages have a placeholder because I simply didn't run the bot to collect the data needed. Afaik, very few people play on the other languages (like most of the times you will get placed into an empty room) so I decided not to disrupt the few individuals who actually wanted to play.

**Comment by ghost** [comment]
`jump rope` is 8 characters without the space. Hopefully someone else doesn't ask you why you're right and wrong at the same time.

Referencing your `README.md` file.
